from django.db import models


class SudokuGenerate(models.Model):
    id = models.AutoField(primary_key=True)
    row1_1 = models.IntegerField(default=None, null=True, blank=True)
    row1_2 = models.IntegerField(default=None, null=True, blank=True)
    row1_3 = models.IntegerField(default=None, null=True, blank=True)
    row1_4 = models.IntegerField(default=None, null=True, blank=True)
    row1_5 = models.IntegerField(default=None, null=True, blank=True)
    row1_6 = models.IntegerField(default=None, null=True, blank=True)
    row1_7 = models.IntegerField(default=None, null=True, blank=True)
    row1_8 = models.IntegerField(default=None, null=True, blank=True)
    row1_9 = models.IntegerField(default=None, null=True, blank=True)
    row2_1 = models.IntegerField(default=None, null=True, blank=True)
    row2_2 = models.IntegerField(default=None, null=True, blank=True)
    row2_3 = models.IntegerField(default=None, null=True, blank=True)
    row2_4 = models.IntegerField(default=None, null=True, blank=True)
    row2_5 = models.IntegerField(default=None, null=True, blank=True)
    row2_6 = models.IntegerField(default=None, null=True, blank=True)
    row2_7 = models.IntegerField(default=None, null=True, blank=True)
    row2_8 = models.IntegerField(default=None, null=True, blank=True)
    row2_9 = models.IntegerField(default=None, null=True, blank=True)
    row3_1 = models.IntegerField(default=None, null=True, blank=True)
    row3_2 = models.IntegerField(default=None, null=True, blank=True)
    row3_3 = models.IntegerField(default=None, null=True, blank=True)
    row3_4 = models.IntegerField(default=None, null=True, blank=True)
    row3_5 = models.IntegerField(default=None, null=True, blank=True)
    row3_6 = models.IntegerField(default=None, null=True, blank=True)
    row3_7 = models.IntegerField(default=None, null=True, blank=True)
    row3_8 = models.IntegerField(default=None, null=True, blank=True)
    row3_9 = models.IntegerField(default=None, null=True, blank=True)
    row4_1 = models.IntegerField(default=None, null=True, blank=True)
    row4_2 = models.IntegerField(default=None, null=True, blank=True)
    row4_3 = models.IntegerField(default=None, null=True, blank=True)
    row4_4 = models.IntegerField(default=None, null=True, blank=True)
    row4_5 = models.IntegerField(default=None, null=True, blank=True)
    row4_6 = models.IntegerField(default=None, null=True, blank=True)
    row4_7 = models.IntegerField(default=None, null=True, blank=True)
    row4_8 = models.IntegerField(default=None, null=True, blank=True)
    row4_9 = models.IntegerField(default=None, null=True, blank=True)
    row5_1 = models.IntegerField(default=None, null=True, blank=True)
    row5_2 = models.IntegerField(default=None, null=True, blank=True)
    row5_3 = models.IntegerField(default=None, null=True, blank=True)
    row5_4 = models.IntegerField(default=None, null=True, blank=True)
    row5_5 = models.IntegerField(default=None, null=True, blank=True)
    row5_6 = models.IntegerField(default=None, null=True, blank=True)
    row5_7 = models.IntegerField(default=None, null=True, blank=True)
    row5_8 = models.IntegerField(default=None, null=True, blank=True)
    row5_9 = models.IntegerField(default=None, null=True, blank=True)
    row6_1 = models.IntegerField(default=None, null=True, blank=True)
    row6_2 = models.IntegerField(default=None, null=True, blank=True)
    row6_3 = models.IntegerField(default=None, null=True, blank=True)
    row6_4 = models.IntegerField(default=None, null=True, blank=True)
    row6_5 = models.IntegerField(default=None, null=True, blank=True)
    row6_6 = models.IntegerField(default=None, null=True, blank=True)
    row6_7 = models.IntegerField(default=None, null=True, blank=True)
    row6_8 = models.IntegerField(default=None, null=True, blank=True)
    row6_9 = models.IntegerField(default=None, null=True, blank=True)
    row7_1 = models.IntegerField(default=None, null=True, blank=True)
    row7_2 = models.IntegerField(default=None, null=True, blank=True)
    row7_3 = models.IntegerField(default=None, null=True, blank=True)
    row7_4 = models.IntegerField(default=None, null=True, blank=True)
    row7_5 = models.IntegerField(default=None, null=True, blank=True)
    row7_6 = models.IntegerField(default=None, null=True, blank=True)
    row7_7 = models.IntegerField(default=None, null=True, blank=True)
    row7_8 = models.IntegerField(default=None, null=True, blank=True)
    row7_9 = models.IntegerField(default=None, null=True, blank=True)
    row8_1 = models.IntegerField(default=None, null=True, blank=True)
    row8_2 = models.IntegerField(default=None, null=True, blank=True)
    row8_3 = models.IntegerField(default=None, null=True, blank=True)
    row8_4 = models.IntegerField(default=None, null=True, blank=True)
    row8_5 = models.IntegerField(default=None, null=True, blank=True)
    row8_6 = models.IntegerField(default=None, null=True, blank=True)
    row8_7 = models.IntegerField(default=None, null=True, blank=True)
    row8_8 = models.IntegerField(default=None, null=True, blank=True)
    row8_9 = models.IntegerField(default=None, null=True, blank=True)
    row9_1 = models.IntegerField(default=None, null=True, blank=True)
    row9_2 = models.IntegerField(default=None, null=True, blank=True)
    row9_3 = models.IntegerField(default=None, null=True, blank=True)
    row9_4 = models.IntegerField(default=None, null=True, blank=True)
    row9_5 = models.IntegerField(default=None, null=True, blank=True)
    row9_6 = models.IntegerField(default=None, null=True, blank=True)
    row9_7 = models.IntegerField(default=None, null=True, blank=True)
    row9_8 = models.IntegerField(default=None, null=True, blank=True)
    row9_9 = models.IntegerField(default=None, null=True, blank=True)


class SudokuDetail(models.Model):
    id = models.AutoField(primary_key=True)
    id_sudoku = models.ForeignKey(SudokuGenerate, on_delete='CASCADE')
    desc = models.CharField(max_length=30)
    aud_user = models.CharField(max_length=15)
    aud_fecha_ini = models.DateTimeField(auto_now_add=True)
    aud_fecha_fin = models.DateTimeField()
    state = models.IntegerField()
